apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-4-pods
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deployment-with-4-pods
  template:
    metadata:
      labels:
        app: deployment-with-4-pods
    spec:
      containers:
      - name: ngingx-container
        image: nginxdemos/hello
        ports:
        - containerPort: 80

