apiVersion: v1
kind: Pod
metadata:
  name: tc-node
spec:
  containers:
    - name: dind-container
      image: docker:23.0.1-dind-alpine3.17
      command: [dockerd-entrypoint.sh]
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
    - name: testcontainers-node
      image: demo-registry:5000/10-tc-node-in-k3d:0.1
      command: ["sh", "-c"]
      args: ["dockerize -wait 'tcp://127.0.0.1:2375' -timeout 30s npm test postgresql-container.test.ts"]
      env:
        - name: DOCKER_HOST
          value: "tcp://127.0.0.1:2375"
      volumeMounts:
        - mountPath: /app/testcontainers-node/jest-test-report
          name: volume
  volumes:
    - name: volume
      hostPath:
        path: /jest-test-report