apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: tc-java-argo
spec:
  entrypoint: tc-java
  templates:
    - name: tc-java
      container:
        image: demo-registry:5000/11-tc-java-argo-workflow:0.1
        command: ["sh", "-c"]
        args:
          ["dockerize -wait 'tcp://127.0.0.1:2375' -timeout 60s gradle test"]
        env:
          - name: DOCKER_HOST
            value: tcp://127.0.0.1:2375
          - name: TESTCONTAINERS_RYUK_DISABLED
            value: "true"
          - name: TESTCONTAINERS_CHECKS_DISABLE
            value: "true"
      sidecars:
        - name: dind-container
          image: docker:23.0.1-dind-alpine3.17
          command: ["dockerd-entrypoint.sh"]
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""