FROM powerman/dockerize:0.19.0 as dockerize
FROM gradle:jdk17-alpine

WORKDIR /app
COPY ./testcontainers-java ./
COPY --from=dockerize /usr/local/bin/dockerize /usr/local/bin/

ENV DOCKER_HOST=tcp://dind-container:2375

WORKDIR /app/examples/redis-backed-cache-testng

CMD dockerize -wait $DOCKER_HOST -timeout 20s gradle test