apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: pgadmin
