apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    component: api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    component: api