apiVersion: v1
kind: Pod
metadata:
  name: tc-python
spec:
  containers:
    - name: dind-container
      image: docker:23.0.1-dind-alpine3.17
      command: [dockerd-entrypoint.sh]
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
    - name: testcontainers-python
      image: demo-registry:5000/09-tc-python-in-k3d:0.1
      command: ["sh", "-c"]
      args: ["dockerize -wait 'tcp://127.0.0.1:2375' -timeout 30s pytest --html=/app/report/report.html"]
      env:
        - name: DOCKER_HOST
          value: "tcp://127.0.0.1:2375"
      volumeMounts:
        - mountPath: /app/report/
          name: volume
  volumes:
    - name: volume
      hostPath:
        path: /report