apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    component: api
spec:
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: spring-boot
          envFrom:
            - configMapRef:
                name: psql-config
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: POSTGRES_PASSWORD
            - name: DB_URL
              value: $(DB_HOST):$(DB_PORT)/$(DB_NAME)
          image: demo-registry:5000/15-springboot-api:0.1 
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
          args:
            - "dockerize -wait tcp://$(DB_HOST):$(DB_PORT) -timeout 60s java -jar api.jar"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
