apiVersion: v1
kind: Pod
metadata:
  name: 04-writer-reader
  labels:
    name: 04-writer-reader
spec:
  containers:
    - name: writer-container
      image: ubuntu
      command: ["sh", "-c"]
      args: ["echo 'content of test file' >/volume/text1.txt && sleep infinity"]
      volumeMounts:
        - mountPath: /volume
          name: demo-volume
    - name: reader-container
      image: demo-registry:5000/06-writer-reader-with-dockerize:0.1
      command:
        [
          "sh",
          "-c",
          "dockerize -wait file:///volume/text1.txt -timeout 20s && cat /volume/text1.txt && sleep infinity",
        ]
      volumeMounts:
        - mountPath: /volume
          name: demo-volume
  volumes:
    - name: demo-volume
      emptyDir: {}
