name: D-01 Hello World Java in Docker

on:
  push:
    paths:
      - "docker/01-hello-world-java-in-docker/**"
      - '.github/workflows/D-01-hello-world-java-in-docker.yml'

env:
  EXPECTED: "Hello world!"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Verify Docker installation
        run: docker version

      - name: Build Docker image
        run: |
          # Build the Docker image
          docker build -t 01-hello-world-java-in-docker:0.1 ./docker/01-hello-world-java-in-docker/src

      - name: Run program in Docker container
        run: |
          # Run the program in a Docker container and capture the output
          OUTPUT=$(docker run --name 01-task 01-hello-world-java-in-docker:0.1)
          echo "OUTPUT=${OUTPUT}" >> $GITHUB_ENV

      - name: Check output
        run: |
          # Compare the output with the expected value and handle failure
          if [[ "${{ env.OUTPUT }}" != "${{ env.EXPECTED }}" ]]; then
            echo "Outputs don't match"
            exit 1
          fi

      - name: Check exit status
        run: |
          CONTAINER_STATUS=$(docker inspect 01-task --format='{{.State.ExitCode}}')
          if [ "$CONTAINER_STATUS" -eq 0 ]; then
            echo "Container exited successfully"
          else
            echo "Container failed with exit status $CONTAINER_STATUS"
            exit 1
          fi
          
