name: D-02 Hello World Java In Docker Optimized

on:
  push:
    paths:
      - 'docker/02-hello-world-java-optimized-in-docker/**'
      - '.github/workflows/D-02-hello-world-java-optimized-in-docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPECTED: "Hello world!"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Verify Docker installation
        run: docker version
      
      - name: Build and Run Hello World Java In Docker Optimized
        run: |
          # Build the Docker image
          docker build -t 02-hello-world-java-in-docker-optimized:0.1 \
          -f ./docker/02-hello-world-java-optimized-in-docker/src/Dockerfile-optimized \
          ./docker/02-hello-world-java-optimized-in-docker/src

          # Run the program in a Docker container and capture the output
          OUTPUT=$(docker run --name 02-task-optimized 02-hello-world-java-in-docker-optimized:0.1)
          echo "OUTPUT=${OUTPUT}" >> $GITHUB_ENV

      - name: Check output
        run: |
          # Compare the output with the expected value and handle failure
          if [[ "${{ env.OUTPUT }}" != "${{ env.EXPECTED }}" ]]; then
            echo "Outputs don't match"
            exit 1
          fi

      - name: Check exit status
        run: |
          CONTAINER_STATUS=$(docker inspect 02-task-optimized --format='{{.State.ExitCode}}')
          if [ "$CONTAINER_STATUS" -eq 0 ]; then
            echo "Container exited successfully"
          else
            echo "Container failed with exit status $CONTAINER_STATUS"
            exit 1
          fi
