name: D-03 Hello World Python In Docker
on:
  push:
    paths:
      - "docker/03-hello-world-python-in-docker/**"
      - ".github/workflows/D-03-hello-world-python-in-docker.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPECTED: "Hello world"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Docker installation
        run: docker version
      
      - name: Build and Run HelloWorldPythonInDocker
        run: |
          docker build -t 03-hello-world-python-in-docker:0.1  ./docker/03-hello-world-python-in-docker/src
          # Parameter '--name' with value 'world' is passed to the python program
          OUTPUT=$(docker run --name 03-task 03-hello-world-python-in-docker:0.1 --name world)
          echo "OUTPUT=${OUTPUT}" >> $GITHUB_ENV

      - name: Check if output matches the expected one
        run: |
          if [[ "${{ env.OUTPUT }}" != "${{ env.EXPECTED }}" ]]; then
          echo "Outputs don't match }}"
          exit 1
          fi

      - name: Check exit status
        run: |
          CONTAINER_STATUS=$(docker inspect 03-task --format='{{.State.ExitCode}}')
          if [ "$CONTAINER_STATUS" -eq 0 ]; then
            echo "Container exited successfully"
          else
            echo "Container failed with exit status $CONTAINER_STATUS"
            exit 1
          fi
