name: D-04 Hello World JS In Docker
on:
  push:
    paths:
      - 'docker/04-hello-world-js-in-docker/**'
      - '.github/workflows/D-04-hello-world-js-in-docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPECTED: "Hello, World!"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Docker installation
        run: docker version
      
      - name: Build and Run HelloWorldJsInDocker
        run: |
          docker build -t 04-hello-world-js-in-docker:0.1  ./docker/04-hello-world-js-in-docker/src
          OUTPUT=$(docker run --name 04-task 04-hello-world-js-in-docker:0.1)
          echo "OUTPUT=${OUTPUT}" >> $GITHUB_ENV

      - name: Check if output matches the expected one
        run: |
          if [[ "${{ env.OUTPUT }}" != "${{ env.EXPECTED }}" ]]; then
          echo "Outputs don't match }}"
          exit 1
          fi

      - name: Check exit status
        run: |
          CONTAINER_STATUS=$(docker inspect 04-task --format='{{.State.ExitCode}}')
          if [ "$CONTAINER_STATUS" -eq 0 ]; then
            echo "Container exited successfully"
          else
            echo "Container failed with exit status $CONTAINER_STATUS"
            exit 1
          fi

