name: D-10 Java Testcontainers with Report Accessible in Docker

on:
  push:
    paths:
      - ".github/workflows/D-10-testcontainers-java-with-report-accessible-from-host.yml"
      - "docker/10-testcontainers-java-with-report-accessible-from-host/**"

env:
  TASK_PATH: "${{ github.workspace }}/docker/10-testcontainers-java-with-report-accessible-from-host"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "USER_ID=$(id -u)" >> $GITHUB_ENV
          echo "GROUP_ID=$(id -g)" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize and update submodule
        run: |
          git submodule update --init --recursive
          cp -r ./submodules/testcontainers-java ${{ env.TASK_PATH }}/src

      - name: Create report folder and check if it was successfully created
        run: |
          mkdir ${{ env.TASK_PATH }}/report
          if [ -d "${{ env.TASK_PATH }}/report" ]; then
            echo "Report folder was created"
            cd ${{ env.TASK_PATH }}
            ls
          else
            echo "Report folder wasn't created"
            exit 1
          fi

      - name: Create network
        run: docker network create demo-network

      - name: Run dind container
        run: |
          docker run --privileged -d -p 12345:2375 --name dind-container -e DOCKER_TLS_CERTDIR="" --network demo-network docker:23.0.1-dind

      - name: Check dind container
        # Checks the status of the Docker-in-Docker container and exits if not running
        run: |
          DIND_STATUS=$(docker inspect -f '{{.State.Status}}' dind-container)
          echo "Dind status: ${DIND_STATUS}"
          if [[ "${DIND_STATUS}" != "running" ]]; then
          echo "Dind container is not running"
          exit 1
          fi

      - name: Build Docker image
        run: |
          docker build -t 10-testcontainers-java:0.1 \
          --build-arg USER_ID=${{ env.USER_ID }} \
          --build-arg GROUP_ID=${{ env.GROUP_ID }} \
          ${{ env.TASK_PATH }}/src

      - name: Run tests in Docker container
        run: |
          docker run --name 10-task \
          --mount type=bind,source=${{ env.TASK_PATH }}/report,destination=/app/examples/redis-backed-cache-testng/build \
          --network demo-network 10-testcontainers-java:0.1 > 10-task-logs.txt
          BUILD_OUTPUT=$(grep "BUILD SUCCESSFUL" 10-task-logs.txt)
          echo "BUILD_OUTPUT=${BUILD_OUTPUT}" >> $GITHUB_ENV

      - name: Extract build status from `10-task` and compare
        # Extracts the build status from the `10-task` container logs and compares it to the expected
        run: |
          if [[ "${{ env.BUILD_OUTPUT }}" == *"BUILD SUCCESSFUL"* ]]; then
            echo "The build is successful"
          else
           echo "The build is failed"
           exit 1
          fi

      - name: Check if `report` folder has report after running tests
        run: |
          if [ -d "${{ env.TASK_PATH }}/report/reports/tests/test" ]; then
            cat ${{ env.TASK_PATH }}/report/reports/tests/test/index.html
          else
            echo "Report folder is empty after running tests"
            exit 1
          fi

      - name: Check report folder rights
        run: |
          folder_path="${{ env.TASK_PATH }}/report"
          user=$(stat -c '%U' $folder_path)
          group=$(stat -c '%G' $folder_path)
          if [[ "$user" == "$(id -un)" && "$group" == "$(id -gn)" ]]; then
          echo "User=$user, $(id -un)"
          echo "Group=$group, $(id -gn)"
          else
          echo "Error: user and group are incorrect"
          exit 1
          fi
