name: K-05 Interconnection via Volume

on:
  push:
    paths:
      - "kubernetes/05-interconnect-containers-via-volume/**"
      - ".github/workflows/K-05-interconnection-via-volume.yml"

env:
  EXPECTED: "content of test file"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup k3d
        uses: rinx/setup-k3d@v0.0.3

      - name: Verify Docker installation
        run: docker version

      - name: Verify Kubernetes installation
        run: k3d --version

      - name: Create cluster with registry
        run: k3d cluster create demo-cluster --registry-create demo-registry:12345

      - name: Check cluster existence
        run: |
          CLUSTER_EXISTS=$(k3d cluster list | grep -c "demo-cluster")
          if [ "$CLUSTER_EXISTS" -eq 1 ]; then
             echo "Cluster exists"
          else
             echo "Cluster does not exist"
             exit 1
          fi

      - name: Apply the manifest
        run: kubectl apply -f ./kubernetes/05-interconnect-containers-via-volume/manifests

      - name: Watch reader container logs
        run: |
          sleep 120
          OUTPUT=$(kubectl logs writer-reader-pod -c reader-container --follow)
          echo "Output: $OUTPUT"
          echo "OUTPUT=${OUTPUT}" >> $GITHUB_ENV

      - name: Compare the output with the expected one
        run: |
          if [[ "${{ env.OUTPUT }}" == "${{ env.EXPECTED }}" ]]; then
            echo "The outputs match"
          else
            echo "The outputs don't match"
          exit 1
          fi
