name: K-07 Dind client and server

on:
  push:
    paths:
      - 'kubernetes/07-dind-client-and-server/**'
      - '.github/workflows/K-07-dind-client-and-server.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup k3d
        uses: nolar/setup-k3d-k3s@v1

      - name: Verify Docker installation
        run: docker version

      - name: Verify Kubernetes installation
        run: k3d --version

      - name: Create cluster with registry
        run: k3d cluster create demo-cluster --registry-create demo-registry:12345

      - name: Check cluster existence
        run: |
          CLUSTER_EXISTS=$(k3d cluster list | grep -c "demo-cluster")
          if [ "$CLUSTER_EXISTS" -eq 1 ]; then
             echo "Cluster exists"
          else
             echo "Cluster does not exist"
             exit 1
           fi

      - name: Apply the service
        run: kubectl apply -f ./kubernetes/07-dind-client-and-server/manifests/dind-service.yaml

      - name: Apply the deployment
        run: kubectl apply -f ./kubernetes/07-dind-client-and-server/manifests/dind-client-and-server.yaml

      - name: Wait for pods to be ready
        run: kubectl wait deployment -n default dind-server-and-client --for=condition=Available --timeout=1m

      - name: Add port to cluster
        run: k3d cluster edit demo-cluster --port-add 8081:8080@loadbalancer
      
      - name: Check connection with nginx 
        run: |
          curl localhost:8081
          HTTP_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" localhost:8081)
          if [[ "$HTTP_RESPONSE" -eq 200 ]]; then
          echo "Successfully connected to nginx. Status $HTTP_RESPONSE "
          else
          echo "Error: Status $HTTP_RESPONSE code"
          exit 1
          fi
