name: K-09 Python Testcontainers with Report Accessible in Docker

on:
  push:
    paths:
      - ".github/workflows/K-09-testcontainers-python-in-k3d.yml"
      - "kubernetes/09-testcontainers-python-in-k3d/**"
env:
  TASK_PATH: "${{ github.workspace }}/kubernetes/09-testcontainers-python-in-k3d"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "USER_ID=$(id -u)" >> $GITHUB_ENV
          echo "GROUP_ID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup k3d
        uses: nolar/setup-k3d-k3s@v1

      - name: Verify Docker installation
        run: docker version

      - name: Verify Kubernetes installation
        run: k3d --version

      - name: Initialize and update submodule
        run: |
          git submodule update --init --recursive
          cp -r ./submodules/testcontainers-python ${{ env.TASK_PATH }}/src

      - name: Create report folder and check if it was successfully created
        run: |
          mkdir ${{ env.TASK_PATH }}/report
          if [ -d "${{ env.TASK_PATH }}/report" ]; then
            echo "Report folder was created"
            ls ${{ env.TASK_PATH }}/report
          else
            echo "Report folder wasn't created"
            exit 1
          fi

      - name: Create cluster with registry
        run: |
          k3d cluster create demo-cluster \
          --registry-create demo-registry:12345 \
          --volume ${{ env.TASK_PATH }}/report:/report

      - name: Check cluster existence
        run: |
          CLUSTER_EXISTS=$(k3d cluster list | grep -c "demo-cluster")
          if [ "$CLUSTER_EXISTS" -eq 1 ]; then
             echo "Cluster exists"
          else
             echo "Cluster does not exist"
             exit 1
          fi

      - name: Build, tag and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.TASK_PATH }}/src
          file: ${{ env.TASK_PATH }}/src/Dockerfile
          push: true
          tags: localhost:12345/09-tc-python-in-k3d:0.1
          build-args: |
            USER_ID=$(id -u)
            GROUP_ID=$(id -g)


      - name: Apply manifest
        run: |
          kubectl apply -f ${{ env.TASK_PATH }}/manifests
          sleep 20

      - name: Watch `testcontainers-python` container logs
        run: |
          kubectl logs tc-python -c testcontainers-python --follow > 09-task-logs.txt
          BUILD_OUTPUT=$(grep "passed" 09-task-logs.txt)
          echo "BUILD_OUTPUT=${BUILD_OUTPUT}" >> $GITHUB_ENV

      - name: Check `testcontainers-python` exit status
        run: |
          CONTAINER_EXIT_CODE=$(kubectl get pod tc-python -n default -o jsonpath='{.status.containerStatuses[?(@.name=="testcontainers-python")].state.terminated.exitCode}')
          if [[ $CONTAINER_EXIT_CODE -eq 0 ]]; then
          echo "Container exited successfully"
            else
            echo "Container did not exit successfully"
          exit 1
          fi

      - name: Extract build status and compare
        run: |
          if [[ "${{ env.BUILD_OUTPUT }}" == *"passed"* ]]; then
            echo "The build is successful"
          else
           echo "The build is failed"
           exit 1
          fi

      - name: Check if `report` folder has report after running tests
        run: |
          if [ -f "${{ env.TASK_PATH }}/report/report.html" ]; then
            cat ${{ env.TASK_PATH }}/report/report.html
          else
            echo "Report folder is empty after running tests"
            exit 1
          fi

      - name: Check report file `report.html` rights
        run: |
           folder_path="${{ env.TASK_PATH }}/report"
           user=$(stat -c '%U' $folder_path)
           group=$(stat -c '%G' $folder_path)
           if [[ "$user" == "$(id -un)" && "$group" == "$(id -gn)" ]]; then
           echo "User=$user, $(id -un)"
           echo "Group=$group, $(id -gn)"
           else
           echo "Error: user and group are incorrect"
           exit 1
           fi
