FROM powerman/dockerize:0.19.0 as dockerize
FROM python:latest

ARG USER_ID=1000
ARG GROUP_ID=1000

ENV USER_ID=${U_ID}
ENV GROUP_ID=${G_ID}
ENV DOCKER_HOST=tcp://dind-container:2375

WORKDIR /app/
COPY --from=dockerize /usr/local/bin/dockerize /usr/local/bin
COPY ./testcontainers-python .

RUN pip install --upgrade pip && pip install pytest
WORKDIR /app/redis
RUN pip install pytest-html
RUN pip install testcontainers-redis

RUN mkdir -p /app/report/python
CMD dockerize -wait $DOCKER_HOST -timeout 30s pytest --html=/app/report/python/report.html && chown -R $USER_ID:$GROUP_ID /app/report