FROM powerman/dockerize:0.19.0 as dockerize
FROM node:slim

ARG USER_ID=1000
ARG GROUP_ID=1000

ENV USER_ID=${USER_ID}
ENV GROUP_ID=${GROUP_ID}
ENV DOCKER_HOST=tcp://dind-container:2375

WORKDIR /app/
COPY --from=dockerize /usr/local/bin/dockerize /usr/local/bin
COPY ./testcontainers-node .
COPY ./jest.config.js .
RUN npm install --save-dev jest-html-reporter

WORKDIR /app/src/modules/postgresql
RUN npm install
RUN mkdir -p /app/report/node

CMD dockerize -wait $DOCKER_HOST -timeout 30s npm test postgresql-container.test.ts && chown -R $USER_ID:$GROUP_ID /app/jest-test-report